apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: application
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-app
        image: quay.apps.cluster-7zn59.7zn59.sandbox1061.opentlc.com/iob_pd/applcations:httpd
        ports:
        - containerPort: 80
